name: Test

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: Say hi
      run: echo Boo
  call-workflow-2-in-local-repo:
    uses: ./.github/workflows/callable.yml
